/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;


import com.geeks.beans.TicketBean;
import com.geeks.dao.TicketDAO;
import com.geeks.dao.TicketDetailsDAO;
import com.geeks.daoImp.TicketDAOImpl;
import com.geeks.daoImp.TicketDetailsDAOImpl;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xyz
 */
public class GetAllTickets extends javax.swing.JFrame {

    public static String ticket="",paid="",contact="";
    public static Date date;
    
    public GetAllTickets() throws SQLException {
        initComponents();
        setTicketTable();
    }
    
    private void setTicketTable() throws SQLException{
        TicketDAO ticketDAO = new TicketDAOImpl();
        String ticket = txtTicketNo.getText();
        TicketBean ticketBean = new TicketBean();
        ticketBean.setBarcode(ticket);
        tableTicket.setModel(buildTableModel(ticketDAO.viewAllTicketResultSet(ticketBean)));
        setTicketDetailsTable();
    }
    
    private void setTicketDetailsTable() throws SQLException{
        String ticket = (String) tableTicket.getValueAt(0, 1);
        TicketDetailsDAO ticketDetailsDAO = new TicketDetailsDAOImpl();
        tableTicketDetails.setModel(buildTableModel(ticketDetailsDAO.viewAllTicketDetailsBeanResultSet2(ticket)));
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTicketDetails = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTicket = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtTicketNo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 242, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Детайли по билетите");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("< Назад");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 180, -1));

        tableTicketDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableTicketDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTicketDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTicketDetailsMouseClicked(evt);
            }
        });
        tableTicketDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableTicketDetailsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableTicketDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 590, 520));

        tableTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTicketMouseClicked(evt);
            }
        });
        tableTicket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableTicketKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableTicket);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, 320));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Баркод:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 40));

        txtTicketNo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtTicketNo.setForeground(new java.awt.Color(0, 153, 153));
        txtTicketNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTicketNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtTicketNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 270, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("Промяна");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 180, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Изтрий");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //DashboardWaterPark df = new DashboardWaterPark();
        //df.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableTicketDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTicketDetailsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableTicketDetailsMouseClicked

    private void tableTicketDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableTicketDetailsKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableTicketDetailsKeyReleased

    private void setAllData(){
        String ticket = (String) tableTicket.getValueAt(tableTicket.getSelectedRow(), 1);
        TicketDetailsDAO ticketDetailsDAO = new TicketDetailsDAOImpl();
        try {
            tableTicketDetails.setModel(buildTableModel(ticketDetailsDAO.viewAllTicketDetailsBeanResultSet2(ticket)));
        } catch (Exception ex) {
            Logger.getLogger(GetAllTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTicketNo.setText(ticket);
    }
    private void tableTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTicketMouseClicked
        // TODO add your handling code here:
        setAllData();
    }//GEN-LAST:event_tableTicketMouseClicked

    private void tableTicketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableTicketKeyReleased
        // TODO add your handling code here:
        setAllData();
    }//GEN-LAST:event_tableTicketKeyReleased

    private void txtTicketNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTicketNoKeyReleased
        try {
            // TODO add your handling code here:
            setTicketTable();
        } catch (SQLException ex) {
            Logger.getLogger(GetAllTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTicketNoKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String serial = (String) tableTicket.getValueAt(tableTicket.getSelectedRow(), 1);
        String contact1 = (String) tableTicket.getValueAt(tableTicket.getSelectedRow(), 2);
        Date date1 = (Date) tableTicket.getValueAt(tableTicket.getSelectedRow(), 3);
        BigDecimal pay = (BigDecimal) tableTicket.getValueAt(tableTicket.getSelectedRow(), 5);
        ticket = serial;
        paid = pay.toString();
        contact = contact1;
        date = date1;
        txtTicketNo.setText(serial);
        this.dispose();
        TicketFrame of;
        try {
            of = new TicketFrame();
            of.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GetAllTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        TicketBean ticketBean = new TicketBean();
        ticketBean.setBarcode(txtTicketNo.getText());
        TicketDAO ticketDAO = new TicketDAOImpl();
        int r = ticketDAO.deleteTicketDetails(ticketBean);
        if(r!=0){
            JOptionPane.showMessageDialog(this, "Ticket deleted!");
            try {
                txtTicketNo.setText("");
                setTicketTable();
            } catch (SQLException ex) {
                Logger.getLogger(GetAllTickets.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Failed!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetAllTickets.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTicket;
    private javax.swing.JTable tableTicketDetails;
    private javax.swing.JTextField txtTicketNo;
    // End of variables declaration//GEN-END:variables

    private static class setVisible {

        public setVisible(boolean b) {
            
        }
    }
}
