/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;

import com.geeks.beans.UserBean;
import com.geeks.dao.UserDAO;
import com.geeks.daoImp.UserDAOImp;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xyz
 */
public class UsersFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserDAO
     */
    public UsersFrame() throws SQLException {
        initComponents();
        setTable();
        setButtons(2);
    }

    public void setTable() throws SQLException {
        UserDAO userDAO = new UserDAOImp();
        tableUserFrame.setModel(buildTableModel(userDAO.viewAllUserResultSet()));
    }

    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        comboYear = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUserFrame = new javax.swing.JTable();
        txtPassword = new javax.swing.JPasswordField();
        txtPassword1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        comboUserType1 = new javax.swing.JComboBox();
        comboDay = new javax.swing.JComboBox();
        comboMon = new javax.swing.JComboBox();
        lblMsg = new javax.swing.JLabel();
        lblMsg1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 242, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(208, 242, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Потребителско име");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 150, 20));

        txtuname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Парола");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 90, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Потвърди парола");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 140, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Ниво на достъп");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 150, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Дата на раждане");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 140, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("За контакт");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 100, 20));

        txtContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 260, -1));

        comboYear.setBackground(new java.awt.Color(0, 153, 153));
        comboYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboYear.setForeground(new java.awt.Color(208, 242, 255));
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        comboYear.setBorder(null);
        jPanel2.add(comboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 100, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(208, 242, 255));
        btnUpdate.setText("Промени");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 130, 30));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(208, 242, 255));
        btnAdd.setText("Добави");
        btnAdd.setBorderPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 140, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(208, 242, 255));
        jButton3.setText("Изчисти");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 180, -1));

        tableUserFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableUserFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUserFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserFrameMouseClicked(evt);
            }
        });
        tableUserFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableUserFrameKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableUserFrame);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 440));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPasswordInputMethodTextChanged(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 260, -1));

        txtPassword1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 260, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(208, 242, 255));
        jButton4.setText("< Назад");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 180, -1));

        comboUserType1.setBackground(new java.awt.Color(0, 153, 153));
        comboUserType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboUserType1.setForeground(new java.awt.Color(208, 242, 255));
        comboUserType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one", "Customer", "Employee", "Admin" }));
        jPanel2.add(comboUserType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 200, 20));

        comboDay.setBackground(new java.awt.Color(0, 153, 153));
        comboDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboDay.setForeground(new java.awt.Color(208, 242, 255));
        comboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDay.setBorder(null);
        jPanel2.add(comboDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 70, 30));

        comboMon.setBackground(new java.awt.Color(0, 153, 153));
        comboMon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboMon.setForeground(new java.awt.Color(208, 242, 255));
        comboMon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        comboMon.setBorder(null);
        jPanel2.add(comboMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 90, 30));

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(204, 0, 51));
        jPanel2.add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 310, -1, -1));

        lblMsg1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMsg1.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(lblMsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 310, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(208, 242, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Скрий паролата");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 260, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(208, 242, 255));
        btnDelete.setText("Изтрий");
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Име и фамилия");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 130, 20));

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 260, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 1130, 600));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Потребители");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void addForOneUpdateForTwo(int one) {
        String fname = txtfname.getText();
        String uname = txtuname.getText();
        String pass = txtPassword.getText();

        String day = comboDay.getSelectedItem().toString();
        int mon = comboMon.getSelectedIndex() + 1;
        String m = mon + "";
        if (mon < 10) {
            m = "0" + mon;
        }

        String year = comboYear.getSelectedItem().toString();
        String dob = year + "-" + m + "-" + day;

        String contact = txtContact.getText();
        String userType = comboUserType1.getSelectedItem().toString();

        int createdBy = UserDAOImp.userId;

        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat();
        df.applyPattern("yyyy-MM-dd");

        String currentDate = df.format(d);

        UserBean userBean = new UserBean();
        userBean.setName(fname);
        userBean.setUserName(uname);
        userBean.setPassword(pass);
        userBean.setDOB(dob);
        userBean.setContact(contact);
        userBean.setUserType(userType);
        
        UserDAO userDAO = new UserDAOImp();
        if (one == 1) {
            if (userDAO.checkUser(userBean)) {
                JOptionPane.showMessageDialog(this, "User name already exits!");
            } else {
                
                userBean.setCreatedBy(createdBy);
                userBean.setCreatedDate(currentDate);
                
                if (userDAO.addUserDetails(userBean) != 0) {
                    try {
                        clearAll();
                        setTable();
                        JOptionPane.showMessageDialog(this, "User added successfully!");
                    } catch (SQLException ex) {
                        Logger.getLogger(UsersFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the user!");
                }
            }
        } else if(one==2) {
            int id = (int) tableUserFrame.getValueAt(tableUserFrame.getSelectedRow(), 0);
            
            userBean.setModifiedBy(createdBy);
            userBean.setModifiedDate(currentDate);
            userBean.setUseriD(id);
            
            if (userDAO.updateUserDetails(userBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    setButtons(2);
                    JOptionPane.showMessageDialog(this, "User updated successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(UsersFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the user!");
            }
        }else if(one==3){
                int id = (int) tableUserFrame.getValueAt(tableUserFrame.getSelectedRow(), 0);
                userBean.setUseriD(id);
                if (userDAO.deleteUserDetails(userBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    setButtons(2);
                    JOptionPane.showMessageDialog(this, "User deleted successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(UsersFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the user!");
            }
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(1);
    }//GEN-LAST:event_btnAddActionPerformed

    private void tableUserFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserFrameMouseClicked
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableUserFrameMouseClicked

    private void tableUserFrameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableUserFrameKeyReleased
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableUserFrameKeyReleased

    private void txtPasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPasswordInputMethodTextChanged
        // TODO add your handling code here:
        String ftxt = txtPassword1.getText();
        String ltxt = txtPassword.getText();
        if (ftxt.equals(ltxt)) {
            lblMsg.setText("Correct");
        } else {
            lblMsg.setText("Wrong");
        }
    }//GEN-LAST:event_txtPasswordInputMethodTextChanged

    public void matchPasswords(){
        lblMsg.setText("");
        lblMsg1.setText("");
        String ftxt = txtPassword1.getText();
        String ltxt = txtPassword.getText();
        if (ftxt.equals(ltxt)) {
            lblMsg1.setText("*Match");
        } else {
            lblMsg.setText("*Unmatched!");
        }
    }
    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        matchPasswords();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
       setButtons(2);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected() == false) {
            txtPassword1.setEchoChar((char) 0);
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword1.setEchoChar('*');
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    public void clearAll() {
        txtfname.setText("");
        txtuname.setText("");
        txtPassword1.setText("");
        txtPassword.setText("");

        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat();
        df.applyPattern("yyyy-MM-dd");

        String date[] = df.format(d1).split("-");
        comboDay.setSelectedItem(date[2]);
        comboMon.setSelectedIndex(Integer.parseInt(date[1]) - 1);
        comboYear.setSelectedItem(date[0]);
        txtContact.setText("");
        comboUserType1.setSelectedItem("Select one");
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(2);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(3);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void setButtons(int val){
        if(val==1){
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        }else{
            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }
    
    public void setAllTxts() {
        matchPasswords();
        setButtons(1);
        int id = (int) tableUserFrame.getValueAt(tableUserFrame.getSelectedRow(), 0);
        UserBean userBean = new UserBean();
        userBean.setUseriD(id);
        UserDAO userDAO = new UserDAOImp();
        ArrayList<UserBean> list = (ArrayList<UserBean>) userDAO.setAllTxt(userBean);
        for (UserBean userBean1 : list) {
            txtfname.setText(userBean1.getName());
            txtuname.setText(userBean1.getUserName());
            txtPassword1.setText(userBean1.getPassword());
            txtPassword.setText(userBean1.getPassword());
            String date[] = userBean1.getDOB().split("-");
            comboDay.setSelectedItem(date[2]);
            comboMon.setSelectedIndex(Integer.parseInt(date[1]) - 1);
            comboYear.setSelectedItem(date[0]);
            txtContact.setText(userBean1.getContact());
            comboUserType1.setSelectedItem(userBean1.getUserType());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox comboDay;
    private javax.swing.JComboBox comboMon;
    private javax.swing.JComboBox comboUserType1;
    private javax.swing.JComboBox comboYear;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblMsg1;
    private javax.swing.JTable tableUserFrame;
    private javax.swing.JTextField txtContact;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables

    private static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
